hl.on("hyprland.start", function()
    hl.exec_cmd("awww-daemon")
    hl.exec_cmd("gnome-keyring-daemon --start --components=secrets")
    hl.exec_cmd("/usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 || /usr/libexec/polkit-gnome-authentication-agent-1")
    hl.exec_cmd("hypridle")
    hl.exec_cmd("dbus-update-activation-environment --all")
    hl.exec_cmd("hyprpm reload")
    hl.exec_cmd("hyprctl setcursor McMojave 24")
    hl.exec_cmd("gsettings set org.gnome.desktop.interface font-name 'Geist'")
    hl.exec_cmd("gsettings set org.gnome.desktop.interface document-font-name 'Geist'")
    hl.exec_cmd("gsettings set org.gnome.desktop.interface monospace-font-name 'Geist Mono'")
    hl.exec_cmd("gsettings set org.gnome.desktop.wm.preferences titlebar-font 'Geist'")
    hl.exec_cmd("easyeffects --gapplication-service")
    hl.exec_cmd("wl-paste --type text --watch cliphist store")
    hl.exec_cmd("wl-paste --type image --watch cliphist store")
    hl.exec_cmd("waybar")
    hl.exec_cmd("helium-browser")
    hl.exec_cmd("hyprsunset")
    hl.exec_cmd("swaync")
    hl.exec_cmd("~/.config/hypr/scripts/battery-notify.sh")
    hl.exec_cmd("EMOJI_FONT=AppleColorEmoji vicinae server")
end)