# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'

add_newline = true
palette = "catppuccin_mocha"

format = """
[](bold blue) $directory$git_branch$git_status
$username$hostname$nodejs$python$rust$golang$docker$package$battery$cmd_duration
$character
"""

# 🎨 Palette Catppuccin Mocha
[palettes.catppuccin_mocha]
blue = "#89b4fa"
red = "#f38ba8"
green = "#a6e3a1"
yellow = "#f9e2af"
purple = "#cba6f7"
cyan = "#94e2d5"
pink = "#f5c2e7"
subtext = "#a6adc8"

# 📂 Directory
[directory]
style = "bold cyan"
truncation_length = 3
truncation_symbol = "/"
truncate_to_repo = true
read_only = " "
format = "[$path]($style)[$read_only]($style) "

# 👤 Username
[username]
style_user = "bold white"
style_root = "bold blue"
format = "[$user]($style) "
show_always = true

# 🌐 Hostname
[hostname]
ssh_only = false
format = "on [$hostname](bold red) "
trim_at = ".companyname.com"
disabled = false

# 🦀 Rust
[rust]
format = "[via ⚙️ $version](red bold)"

# 🛡️ Sudo
[sudo]
style = "bold green"
symbol = "👑 "
disabled = false

# 🌱 Git
[git_branch]
symbol = " "
style = "bold purple"
format = "[$symbol$branch]($style) "

[git_status]
style = "bold red"
conflicted = "🏳 "
ahead = "⇡${count} "
diverged = "⇕⇡${ahead_count}⇣${behind_count} "
behind = "⇣${count} "
up_to_date = "✓"
untracked = "🤷 "
stashed = "📦 "
modified = "📝 "
staged = "[++($count)](green) "
renamed = "👅 "
deleted = "🗑 "

[git_commit]
commit_hash_length = 4
tag_symbol = "🔖 "

# 💻 Node.js
[nodejs]
symbol = " "
style = "bold green"
format = "[$symbol($version)]($style)"

# 🐍 Python
[python]
symbol = " "
style = "bold yellow"
format = "[$symbol($version)]($style)"

# 🤓 Golang
[golang]
symbol = "🐹 "
style = "bold cyan"
format = "[$symbol($version)]($style)"

# 🐳 Docker
[docker_context]
symbol = " "
style = "bold blue"
format = "[$symbol$context]($style)"

# 📦 Package
[package]
symbol = " "
style = "bold pink"
format = "[$symbol$version]($style)"

# 🔋 Battery
[battery]
full_symbol = "🔋 "
charging_symbol = "⚡ "
discharging_symbol = "💀 "
unknown_symbol = " "
format = "[$symbol$percentage]($style)"

[[battery.display]]
threshold = 20
style = "bold red"

# ⏱️ Command execution time
[cmd_duration]
min_time = 100 
format = " took [$duration]($style)"
style = "bold yellow"

# ➜ Prompt symbol
[character]
success_symbol = "[➜](bold green)"
error_symbol = "[✗](bold red)"
vicmd_symbol = "[](bold green)"