import type { Metadata } from 'next';
import './globals.css';
import { ThemeProvider } from '@/components/theme-provider';
import { ToastProvider, ToastViewport } from '@/components/ui/toast';
import Providers from '@/components/session-provider';
import Navbar from '@/components/layout/navbar';

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<body>
				<Providers>
					<ThemeProvider attribute="class" defaultTheme="dark" enableSystem disableTransitionOnChange>
						<ToastProvider>
							<Navbar />
							{children}
							<ToastViewport />
						</ToastProvider>
					</ThemeProvider>
				</Providers>
			</body>
		</html>
	);
}
