import type { Metadata } from 'next';
import { JetBrains_Mono } from 'next/font/google';
import './globals.css';
import { ThemeProvider } from '@/components/theme-provider';
import { ToastProvider, ToastViewport } from '@/components/ui/toast';
import { SessionProvider } from 'next-auth/react';
import { getServerSession } from 'next-auth';
import { authOptions } from '@/libs/auth';

const jetBrainsMono = JetBrains_Mono({
	variable: '--font-jetbrains-mono',
	subsets: ['latin-ext'],
});

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
};

export default async function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	const session = await getServerSession(authOptions); // Ambil session di server

	return (
		<html lang="en">
			<body className={`${jetBrainsMono.variable} antialiased`}>
				<SessionProvider session={session}>
					<ThemeProvider attribute="class" defaultTheme="dark" enableSystem disableTransitionOnChange>
						<ToastProvider>
							{children}
							<ToastViewport />
						</ToastProvider>
					</ThemeProvider>
				</SessionProvider>
			</body>
		</html>
	);
}
