import type { Metadata } from 'next';
import { JetBrains_Mono } from 'next/font/google';
import './globals.css';
import { ThemeProvider } from '@/components/theme-provider';
import { ToastProvider, ToastViewport } from '@/components/ui/toast';
import { getServerSession } from 'next-auth';
import { authOptions } from './api/user/login/route';
import Providers from '@/components/session-provider';

const jetBrainsMono = JetBrains_Mono({
	variable: '--font-jetbrains-mono',
	subsets: ['latin-ext'],
});

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
};

export default async function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	// Ambil session di server dengan authOptions

	return (
		<html lang="en">
			<body className={`${jetBrainsMono.variable} antialiased`}>
				<Providers>
					<ThemeProvider attribute="class" defaultTheme="dark" enableSystem disableTransitionOnChange>
						<ToastProvider>
							{children}
							<ToastViewport />
						</ToastProvider>
					</ThemeProvider>
				</Providers>
			</body>
		</html>
	);
}
